services:
  rabbitmq: 
    image: rabbitmq:4.0.7-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 6s
      timeout: 3s
      retries: 5