
services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=2GB
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    # environment:
    #   - GF_SECURITY_ADMIN_USER=admin
    #   - GF_SECURITY_ADMIN_PASSWORD=admin123

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    # pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    ports:
      - "9100:9100"
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    # volumes:
    #   - /:/rootfs:ro
    #   - /run:/run:ro
    #   - /sys:/sys:ro
    #   - /var/lib/docker/:/var/lib/docker:ro
    #   - /dev/disk/:/dev/disk:ro
    # devices:
    #   - /dev/kmsg
    # restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  
  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - 6379:6379

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
