services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123

  app:
    build: .
    ports:
      - 8000:8000
  
  