services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # volumes:
    #   - ./pgData:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8000:8000

volumes:
  postgres_data:
  