services:
  redis:
    image: redis:7.4.0
    ports:
      - '6379:6379'

  app:
    build: .
    volumes:
      - .:/app # Changes in the host directory immediately visible inside the container.
      - /app/node_modules # Avoid overriding node_modules


# --> docker compose up
# --> docker compose down