
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--innodb-buffer-pool-size=1G",
        "--innodb-log-file-size=256M",
        "--max-connections=500",
        "--slow-query-log=1",
        "--long-query-time=1"
      ]

    volumes:
      - mysql_ingest_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      # - ./mysql/conf:/etc/mysql/conf.d
  
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # ---- KRaft settings ----
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ---- Listeners ----
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_NUM_PARTITIONS: 3

      # ---- Storage ----
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: unless-stopped
    depends_on:
      - kafka

  # ----------------- Kibana -----------------
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  mysql_ingest_data:
  kafka_data:
  es_data:

# docker exec -it <containerid> bash
# mysql -u admin -p cscan