services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # gofiber-gorm:
  #   build: ./gofiber-gorm
  #   ports:
  #     - "8082:8082"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1.0"
  #         memory: 256M
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #   networks:
  #     - monitoring
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
    
  # gofiber-pgx:
  #   build: ./gofiber-pgx
  #   ports:
  #     - "8083:8083"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1.0"
  #         memory: 256M
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #   networks:
  #     - monitoring
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # fastapi-api:
  #   build: ./fastapi
  #   ports:
  #     - "8084:8084"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1.0"
  #         memory: 256M
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #   networks:
  #     - monitoring
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  

volumes:
  pg_data:

networks:
  monitoring:
    external: true