services:
  postgres:
    image: postgres:16.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7.4.0
    ports:
      - '6379:6379'


# --> docker compose up
# --> docker compose down